# Generated by Django 5.2.11 on 2026-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('customer_id', models.IntegerField()),
                ('shipping_method', models.CharField(choices=[('standard', 'Tieu chuan 3-5 ngay'), ('express', 'Nhanh 1-2 ngay')], default='standard', max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Cho giao'), ('shipping', 'Dang giao'), ('delivered', 'Da giao'), ('failed', 'That bai')], default='pending', max_length=20)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
    ]
