# Generated by Django 4.2.29 on 2026-03-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('customer_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cod', 'COD - Thu tien khi giao'), ('bank', 'Chuyen khoan ngan hang'), ('card', 'The tin dung / ghi no')], default='cod', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Cho xu ly'), ('completed', 'Da thanh toan'), ('failed', 'That bai'), ('refunded', 'Hoan tien')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
